#
# https://tox.wiki/en/latest/config.html
#

[tox]
envlist = lint

skipsdist = True
skip_install = True

[testenv:lint]
description = Run all tests
deps =
  {[testenv:yamllint]deps}
  {[testenv:flake8]deps}
commands =
  {[testenv:flake8]commands}
  {[testenv:yamllint]commands}

[testenv:yamllint]
description = A linter for YAML files
deps =
  yamllint
commands = yamllint --strict --list-files {posargs:.}

[testenv:flake8]
description = A python tool that glues together pycodestyle, pyflakes, mccabe, and
            third-party plugins to check the style and quality of some python code
deps =
  flake8
commands = flake8 --color=always {posargs:.}

# https://flake8.pycqa.org/en/latest/user/configuration.html
[flake8]
max-line-length = 120
show-source = True
extend-exclude =
  .venv,
  venv,
