http2 on;
ssl_protocols TLSv1.2 TLSv1.3;
ssl_ecdh_curve X25519:prime256v1:secp384r1;
ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305;
ssl_prefer_server_ciphers off;
ssl_session_timeout 1d;
ssl_session_cache shared:MozSSL:10m;  # about 40000 sessions
add_header Strict-Transport-Security "max-age=63072000" always;  # HSTS (ngx_http_headers_module is required) (63072000 seconds)

# RealIP
set_real_ip_from unix:;
real_ip_header proxy_protocol;

# Nextcloud decoy website
location = / {
    if ($request_method != GET) {
        return 405;
    }
    return 302 https://$host/login;
}
location / {
    root /nextcloud/html;
    index index.html;
    # Security (like in real Nextcloud)
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header Referrer-Policy "no-referrer" always;
    add_header X-Robots-Tag "noindex, nofollow" always;
    location = /status.php {
        default_type application/json;
        add_header X-Powered-By "PHP/8.3.30";
        etag off;
    }
    location = /login {
        add_header X-Powered-By "PHP/8.3.30";
        etag off;
        if ($request_method = POST) {
            return 303 https://$host/login?direct=1&user=user;
        }
        try_files /login.html =404;
    }
    location = /login/webauthn/start {
        add_header X-Powered-By "PHP/8.3.30";
        etag off;
        default_type application/json;
        if ($request_method = POST) {
            return 200 "{
    \"challenge\": \"Gq0GAOHnJOG9WCuKxnAQP8Kq4hpjw9aF59UATIF2vCk=\",
    \"rpId\": \"$host\",
    \"userVerification\": \"required\",
    \"timeout\": 60000
}";
        }
        return 405 '{"message":"Not Allowed"}';
    }
    location = /lostpassword/email {
        default_type application/json;
        add_header X-Powered-By "PHP/8.3.30";
        etag off;
        if ($request_method = POST) {
            return 200 '{"status":"success"}';
        }
    }
    location /csrftoken {
        default_type application/json;
        add_header X-Powered-By "PHP/8.3.30";
        etag off;
        return 200 '{"token":"Ue4zM5nRbNjUd1u7lUAkaYqBiFEhiuDX1odJNswk93s=:Gq0GAOHnJOG9WCuKxnAQP8Kq4hpjw9aF59UATIF2vCk="}';
    }
    location ~ ^/\.well-known/(carddav|caldav)$ {
        add_header X-Powered-By "PHP/8.3.30";
        etag off;
        return 301 https://$host/remote.php/dav/;
    }
    location /remote.php/dav/ {
        default_type application/xml;
        return 401 "<?xml version=\"1.0\" encoding=\"utf-8\"?>
<d:error xmlns:d=\"DAV:\" xmlns:s=\"http://sabredav.org/ns\">
  <s:exception>Sabre\DAV\Exception\NotAuthenticated</s:exception>
  <s:message>No public access to this resource., AppAPIAuth has not passed, This request is not for a federated calendar, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Bearer' header found. Either the client didn't send one, or the server is mis-configured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured</s:message>
</d:error>\n";
    }
    location /_errors/ {
        return 404;
    }
}

error_page 403 /index.php/error/403;
location = /index.php/error/403 {
    alias /nextcloud/html/index.php/error/403.html;
    default_type text/html;
    add_header X-Powered-By "PHP/8.3.30";
    etag off;
}

error_page 404 /index.php/error/404;
location = /index.php/error/404 {
    alias /nextcloud/html/index.php/error/404.html;
    default_type text/html;
    add_header X-Powered-By "PHP/8.3.30";
    etag off;
}
location ~ ^/index\.php/error/.*\.html$ {
    return 404;
}
