---
x-container: &container
  restart: always
  read_only: true
  cap_drop:
    - ALL
  security_opt:
    - no-new-privileges=true
  pids_limit: 100
  ulimits:
    core: 0  # Prevent core dumps
  logging:
    driver: json-file
    options:
      max-size: 200k
      max-file: "10"

name: marzneshin
services:
  migrator:
    <<: *container
    image: ghcr.io/metajiji/docker-marzneshin/migrator:latest
    user: nonroot:nonroot
    env_file:
      - migrator.env
    tmpfs:
      - /tmp
    volumes:
      - migrator_data:/app/data
      - migrator_log:/app/log

volumes:
  migrator_data:
  migrator_log:

networks:
  default:
    name: $COMPOSE_PROJECT_NAME
