---
x-container: &container
  restart: always
  read_only: true
  cap_drop:
    - ALL
  security_opt:
    - no-new-privileges=true
  pids_limit: 100
  ulimits:
    core: 0  # Prevent core dumps
  logging:
    driver: json-file
    options:
      max-size: 200k
      max-file: "10"

name: marzneshin
services:
  panel:
    <<: *container
    image: ghcr.io/metajiji/docker-marzneshin/panel:latest
    user: nonroot:nonroot
    env_file:
      - panel.env
    tmpfs:
      - /tmp
    volumes:
      - panel_data:/app/data

volumes:
  panel_data:
